baseURL: https://example.com
title: KP Med Analytics Insights
theme: hugo-theme-m10c
paginate: 8
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 2
    - identifier: about
      name: About
      url: /about/
      weight: 3
params:
  author: Keletso Phohlo
  description: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
  menu_item_separator: ' - '
  social:
    - icon: Email
      name: Email
      url: "mailto:kellzphohlo@proton.me""
    - icon: LinkedIn
      name: LinkedIn
      url: "https://www.linkedin.com/in/keletso-phohlo-348408234/ target = '_blank'"

